osx_image: xcode9.4
language: swift
script:
  - xcodebuild clean test -workspace MyParentsOnBoard.xcworkspace -scheme MyParentsOnBoard -destination "platform=iOS Simulator,name=iPhone 8,OS=12.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
